import Cerb5
import json
#from xml.etree  import ElementTree as etree
api = Cerb5.API('steve@localhost','linuxx','http://192.168.101.142/helpdesk/index.php/rest')
#tree = etree.fromstring(api.post('tickets/search', {}))
x = json.loads(api.post('tickets/search', {}))
print x
print x['__status']
#def parse(tree, depth=0):
#  for element in tree:
#    print depth, element.tag, element.attrib['key'], element.text
#    if element.tag == 'array':
#      parse(element, depth+1)

#parse(tree)
# OUT: 0 string __status success
# OUT: 0 string total 26
# OUT: 0 string count 10
# OUT: 0 string page 1
# OUT: 0 array results None
# OUT: 1 array 1 None
# OUT: 2 string id 1
# OUT: 2 string mask GNG-64439-319
# OUT: 2 string subject Welcome to Cerberus Helpdesk 5.x!
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276111871
# OUT: 2 string updated 1276111871
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276111871
# OUT: 2 string initial_message_id 1
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 1093
# OUT: 2 string initial_message_ticket_id 1
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 2
# OUT: 2 string initial_message_sender_address support@webgroupmedia.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276111871
# OUT: 2 string latest_message_id 1
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 1093
# OUT: 2 string latest_message_ticket_id 1
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 2
# OUT: 2 string latest_message_sender_address support@webgroupmedia.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 15 None
# OUT: 2 string id 15
# OUT: 2 string mask EUX-43613-816
# OUT: 2 string subject How long for new economy hosting?
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 15
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 108
# OUT: 2 string initial_message_ticket_id 15
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 15
# OUT: 2 string initial_message_sender_address laura.lopez@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 15
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 108
# OUT: 2 string latest_message_ticket_id 15
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 15
# OUT: 2 string latest_message_sender_address laura.lopez@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 16 None
# OUT: 2 string id 16
# OUT: 2 string mask FNL-46959-362
# OUT: 2 string subject different options for dedicated hosting?
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 16
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 117
# OUT: 2 string initial_message_ticket_id 16
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 16
# OUT: 2 string initial_message_sender_address maria.green@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 16
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 117
# OUT: 2 string latest_message_ticket_id 16
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 16
# OUT: 2 string latest_message_sender_address maria.green@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 17 None
# OUT: 2 string id 17
# OUT: 2 string mask TAS-36853-347
# OUT: 2 string subject Hosting Industry Newsletter (The Future of Java?)
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 17
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 293
# OUT: 2 string initial_message_ticket_id 17
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 6
# OUT: 2 string initial_message_sender_address hosting-news@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 17
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 293
# OUT: 2 string latest_message_ticket_id 17
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 6
# OUT: 2 string latest_message_sender_address hosting-news@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 18 None
# OUT: 2 string id 18
# OUT: 2 string mask VWF-71812-119
# OUT: 2 string subject my money back?
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 18
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 86
# OUT: 2 string initial_message_ticket_id 18
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 17
# OUT: 2 string initial_message_sender_address michael.miller@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 18
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 86
# OUT: 2 string latest_message_ticket_id 18
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 17
# OUT: 2 string latest_message_sender_address michael.miller@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 19 None
# OUT: 2 string id 19
# OUT: 2 string mask DKY-49467-165
# OUT: 2 string subject manual?
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 19
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 70
# OUT: 2 string initial_message_ticket_id 19
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 18
# OUT: 2 string initial_message_sender_address carol.young@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 19
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 70
# OUT: 2 string latest_message_ticket_id 19
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 18
# OUT: 2 string latest_message_sender_address carol.young@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 20 None
# OUT: 2 string id 20
# OUT: 2 string mask PWK-95685-434
# OUT: 2 string subject Need help
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 20
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 53
# OUT: 2 string initial_message_ticket_id 20
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 19
# OUT: 2 string initial_message_sender_address deborah.jackson@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 20
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 53
# OUT: 2 string latest_message_ticket_id 20
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 19
# OUT: 2 string latest_message_sender_address deborah.jackson@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 21 None
# OUT: 2 string id 21
# OUT: 2 string mask QZJ-94754-451
# OUT: 2 string subject How can I pay?
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 21
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 73
# OUT: 2 string initial_message_ticket_id 21
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 20
# OUT: 2 string initial_message_sender_address ruth.hill@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 21
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 73
# OUT: 2 string latest_message_ticket_id 21
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 20
# OUT: 2 string latest_message_sender_address ruth.hill@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 22 None
# OUT: 2 string id 22
# OUT: 2 string mask ULD-77136-878
# OUT: 2 string subject New Order: fitness.com (Copper package)
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 22
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 95
# OUT: 2 string initial_message_ticket_id 22
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 14
# OUT: 2 string initial_message_sender_address hosting-orders@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 22
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 95
# OUT: 2 string latest_message_ticket_id 22
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 14
# OUT: 2 string latest_message_sender_address hosting-orders@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None
# OUT: 1 array 23 None
# OUT: 2 string id 23
# OUT: 2 string mask WBN-27184-277
# OUT: 2 string subject New Order: finance.com (Copper package)
# OUT: 2 string next_worker_id 0
# OUT: 2 string created 1276112529
# OUT: 2 string updated 1276112529
# OUT: 2 array custom None
# OUT: 2 string group_id 627
# OUT: 2 string group_name Dispatch
# OUT: 2 string initial_message_created 1276112529
# OUT: 2 string initial_message_id 23
# OUT: 2 string initial_message_is_outgoing 0
# OUT: 2 string initial_message_storage_size 95
# OUT: 2 string initial_message_ticket_id 23
# OUT: 2 string initial_message_worker_id 0
# OUT: 2 string initial_message_sender_id 14
# OUT: 2 string initial_message_sender_address hosting-orders@cerberusdemo.com
# OUT: 2 string initial_message_sender_num_spam 0
# OUT: 2 string initial_message_sender_num_nonspam 0
# OUT: 2 string initial_message_sender_is_registered 0
# OUT: 2 string initial_message_sender_is_banned 0
# OUT: 2 array initial_message_sender_custom None
# OUT: 2 string latest_message_created 1276112529
# OUT: 2 string latest_message_id 23
# OUT: 2 string latest_message_is_outgoing 0
# OUT: 2 string latest_message_storage_size 95
# OUT: 2 string latest_message_ticket_id 23
# OUT: 2 string latest_message_worker_id 0
# OUT: 2 string latest_message_sender_id 14
# OUT: 2 string latest_message_sender_address hosting-orders@cerberusdemo.com
# OUT: 2 string latest_message_sender_num_spam 0
# OUT: 2 string latest_message_sender_num_nonspam 0
# OUT: 2 string latest_message_sender_is_registered 0
# OUT: 2 string latest_message_sender_is_banned 0
# OUT: 2 array latest_message_sender_custom None